### ISSUE TITLE
Add example that uses NODE_API_ADDON for addon registration

### ISSUE THREAD

**Issue by KevinEady** [nodejs/node-addon-examples#199]
It appears that all of our examples use the `NODE_API_MODULE` macro to register native addons. It would be helpful to add an 
 example that uses `NODE_API_ADDON` registration, where the module extends `Addon<T>`.

**Comment by KevinEady** [comment]
This issue was raised because of a question on node-addon-api on when to use which macro: https://github.com/nodejs/node-addon-api/issues/1190

**Comment by UrielCh** [comment]
Hi,

I want to write a new Binding for openCV, and since I'm writing it from scratch, I want to make it as up-to-date as possible.

So I would like to use `NODE_API_ADDON`

My current sample code is [here](https://github.com/UrielCh/opencv-sandbox/blob/ceonversion/cc-v5/cv_mat_object_addon.cpp)

the code builds fine, but my exported object is empty.

**Comment by gabrielschulhof** [comment]
This issue was resolved in https://github.com/nodejs/node-addon-examples/pull/209.
